import type { Application, SLO, SquadSummary, PlatformSummary } from '@/types'

const makeHistory = (base: number, days = 14) =>
  Array.from({ length: days }, (_, i) => ({
    date: new Date(Date.now() - (days - i) * 86400000).toISOString().split('T')[0],
    score: Math.max(0, Math.min(100, base + (Math.random() - 0.5) * 12)),
  }))

export const applications: Application[] = [
  {
    id: 'payment-api',
    name: 'payment-api',
    namespace: 'production',
    kind: 'Deployment',
    squad: 'payments',
    product: 'Core Banking',
    domain: 'Financial',
    owner: 'payments-team',
    techLead: 'ana.souza@example.com',
    tier: 'tier-1',
    overallScore: 85.2,
    pillarScores: {
      resilience: { score: 88.0, passedChecks: 11, totalChecks: 14 },
      security: { score: 89.3, passedChecks: 3, totalChecks: 4 },
      compliance: { score: 100.0, passedChecks: 3, totalChecks: 3 },
      performance: { score: 71.4, passedChecks: 1, totalChecks: 2 },
      operational: { score: 80.0, passedChecks: 4, totalChecks: 5 },
      cost: { score: 75.0, passedChecks: 3, totalChecks: 4 },
    },
    issues: { critical: 0, errors: 1, warnings: 3 },
    findings: [
      { ruleId: 'PERF-002', ruleName: 'HPA com Target Adequado', severity: 'warning', message: 'HPA target acima do recomendado (92%)', remediation: 'Reduza o HPA target para entre 50-90%', remediable: true },
      { ruleId: 'SEC-002', ruleName: 'ReadOnly Root Filesystem', severity: 'error', message: 'Root filesystem nao e readonly', remediation: 'Configure readOnlyRootFilesystem: true no securityContext', remediable: false },
      { ruleId: 'RES-007', ruleName: 'HPA Configurado', severity: 'warning', message: 'HPA com metricas customizadas nao encontradas', remediation: 'Adicione metricas de CPU/memoria ao HPA', remediable: true },
    ],
    remediationPR: { prNumber: 142, prUrl: 'https://github.com/org/core-banking/pull/142', prBranch: 'titlis/remediation/production-payment-api', status: 'open', issuesFixed: ['RES-007', 'PERF-002'], createdAt: '2024-01-15T10:30:00Z' },
    lastEvaluated: '2024-01-20T14:22:00Z',
    monthlyCostUsd: 840,
    cpuEfficiencyPct: 72,
    memoryEfficiencyPct: 68,
    wasteUsd: 220,
    sloCount: 3,
    sloHealthy: 3,
    trend: 'up',
    scoreHistory: makeHistory(85),
  },
  {
    id: 'order-service',
    name: 'order-service',
    namespace: 'production',
    kind: 'Deployment',
    squad: 'orders',
    product: 'Marketplace',
    domain: 'Commerce',
    owner: 'orders-team',
    techLead: 'carlos.lima@example.com',
    tier: 'tier-1',
    overallScore: 58.4,
    pillarScores: {
      resilience: { score: 58.1, passedChecks: 6, totalChecks: 14 },
      security: { score: 0.0, passedChecks: 0, totalChecks: 4 },
      compliance: { score: 66.7, passedChecks: 2, totalChecks: 3 },
      performance: { score: 85.7, passedChecks: 2, totalChecks: 2 },
      operational: { score: 60.0, passedChecks: 3, totalChecks: 5 },
      cost: { score: 50.0, passedChecks: 2, totalChecks: 4 },
    },
    issues: { critical: 0, errors: 5, warnings: 4 },
    findings: [
      { ruleId: 'SEC-001', ruleName: 'Imagem com Tag Especifica', severity: 'error', message: 'Imagem usando tag :latest', remediation: 'Use tags versionadas (ex: v1.2.3)', remediable: false },
      { ruleId: 'SEC-002', ruleName: 'ReadOnly Root Filesystem', severity: 'error', message: 'Root filesystem nao e readonly', remediation: 'Configure readOnlyRootFilesystem: true', remediable: false },
      { ruleId: 'SEC-003', ruleName: 'Privilege Escalation Desabilitado', severity: 'error', message: 'allowPrivilegeEscalation nao configurado', remediation: 'Configure allowPrivilegeEscalation: false', remediable: false },
      { ruleId: 'SEC-004', ruleName: 'Capabilities Reduzidas', severity: 'error', message: 'Capabilities nao reduzidas', remediation: 'Adicione drop: [ALL] ao securityContext', remediable: false },
      { ruleId: 'RES-007', ruleName: 'HPA Configurado', severity: 'warning', message: 'HPA nao encontrado', remediation: 'Configure HPA para auto-scaling', remediable: true },
      { ruleId: 'RES-013', ruleName: 'Minimo 2 Replicas', severity: 'warning', message: 'Apenas 1 replica configurada', remediation: 'Aumente replicas para pelo menos 2', remediable: true },
    ],
    lastEvaluated: '2024-01-20T13:50:00Z',
    monthlyCostUsd: 1200,
    cpuEfficiencyPct: 45,
    memoryEfficiencyPct: 52,
    wasteUsd: 580,
    sloCount: 2,
    sloHealthy: 1,
    trend: 'down',
    scoreHistory: makeHistory(58),
  },
  {
    id: 'user-auth',
    name: 'user-auth',
    namespace: 'production',
    kind: 'Deployment',
    squad: 'identity',
    product: 'Identity Platform',
    domain: 'Security',
    owner: 'identity-team',
    techLead: 'priya.sharma@example.com',
    tier: 'tier-1',
    overallScore: 93.7,
    pillarScores: {
      resilience: { score: 95.7, passedChecks: 13, totalChecks: 14 },
      security: { score: 100.0, passedChecks: 4, totalChecks: 4 },
      compliance: { score: 100.0, passedChecks: 3, totalChecks: 3 },
      performance: { score: 85.7, passedChecks: 2, totalChecks: 2 },
      operational: { score: 100.0, passedChecks: 5, totalChecks: 5 },
      cost: { score: 75.0, passedChecks: 3, totalChecks: 4 },
    },
    issues: { critical: 0, errors: 0, warnings: 1 },
    findings: [
      { ruleId: 'RES-014', ruleName: 'Estrategia de Rollout', severity: 'warning', message: 'Rollout strategy nao configurada', remediation: 'Configure strategy.type: RollingUpdate', remediable: true },
    ],
    lastEvaluated: '2024-01-20T14:10:00Z',
    monthlyCostUsd: 560,
    cpuEfficiencyPct: 85,
    memoryEfficiencyPct: 82,
    wasteUsd: 60,
    sloCount: 4,
    sloHealthy: 4,
    trend: 'stable',
    scoreHistory: makeHistory(93),
  },
  {
    id: 'notification-worker',
    name: 'notification-worker',
    namespace: 'production',
    kind: 'Deployment',
    squad: 'platform',
    product: 'Platform Infra',
    domain: 'Infrastructure',
    owner: 'platform-team',
    techLead: 'lucas.ferreira@example.com',
    tier: 'tier-2',
    overallScore: 72.1,
    pillarScores: {
      resilience: { score: 75.3, passedChecks: 9, totalChecks: 14 },
      security: { score: 75.0, passedChecks: 3, totalChecks: 4 },
      compliance: { score: 66.7, passedChecks: 2, totalChecks: 3 },
      performance: { score: 71.4, passedChecks: 1, totalChecks: 2 },
      operational: { score: 80.0, passedChecks: 4, totalChecks: 5 },
      cost: { score: 50.0, passedChecks: 2, totalChecks: 4 },
    },
    issues: { critical: 0, errors: 2, warnings: 5 },
    findings: [
      { ruleId: 'RES-012', ruleName: 'NetworkPolicy Aplicada', severity: 'warning', message: 'NetworkPolicy nao encontrada', remediation: 'Crie uma NetworkPolicy para restringir trafego', remediable: false },
      { ruleId: 'RES-008', ruleName: 'HPA com Metricas', severity: 'error', message: 'HPA sem metricas customizadas', remediation: 'Adicione metricas de CPU ao HPA', remediable: true },
      { ruleId: 'COMP-001', ruleName: "Label 'team' obrigatorio", severity: 'error', message: "Label 'team' nao encontrado nos metadados", remediation: "Adicione labels.team: payments ao Deployment", remediable: false },
    ],
    lastEvaluated: '2024-01-20T12:30:00Z',
    monthlyCostUsd: 320,
    cpuEfficiencyPct: 58,
    memoryEfficiencyPct: 61,
    wasteUsd: 120,
    sloCount: 1,
    sloHealthy: 1,
    trend: 'up',
    scoreHistory: makeHistory(72),
  },
  {
    id: 'product-catalog',
    name: 'product-catalog',
    namespace: 'staging',
    kind: 'Deployment',
    squad: 'catalog',
    product: 'Marketplace',
    domain: 'Commerce',
    owner: 'catalog-team',
    techLead: 'marina.costa@example.com',
    tier: 'tier-2',
    overallScore: 91.2,
    pillarScores: {
      resilience: { score: 92.5, passedChecks: 12, totalChecks: 14 },
      security: { score: 96.4, passedChecks: 4, totalChecks: 4 },
      compliance: { score: 100.0, passedChecks: 3, totalChecks: 3 },
      performance: { score: 85.7, passedChecks: 2, totalChecks: 2 },
      operational: { score: 80.0, passedChecks: 4, totalChecks: 5 },
      cost: { score: 87.5, passedChecks: 4, totalChecks: 4 },
    },
    issues: { critical: 0, errors: 0, warnings: 2 },
    findings: [
      { ruleId: 'RES-013', ruleName: 'Minimo 2 Replicas', severity: 'warning', message: 'Apenas 1 replica em staging', remediation: 'Aumente replicas para pelo menos 2', remediable: true },
    ],
    lastEvaluated: '2024-01-20T11:45:00Z',
    monthlyCostUsd: 240,
    cpuEfficiencyPct: 78,
    memoryEfficiencyPct: 74,
    wasteUsd: 45,
    sloCount: 2,
    sloHealthy: 2,
    trend: 'stable',
    scoreHistory: makeHistory(91),
  },
  {
    id: 'analytics-ingestion',
    name: 'analytics-ingestion',
    namespace: 'data',
    kind: 'StatefulSet',
    squad: 'data',
    product: 'Data Platform',
    domain: 'Analytics',
    owner: 'data-team',
    techLead: 'roberto.alves@example.com',
    tier: 'tier-2',
    overallScore: 65.8,
    pillarScores: {
      resilience: { score: 64.5, passedChecks: 7, totalChecks: 14 },
      security: { score: 53.6, passedChecks: 2, totalChecks: 4 },
      compliance: { score: 100.0, passedChecks: 3, totalChecks: 3 },
      performance: { score: 71.4, passedChecks: 1, totalChecks: 2 },
      operational: { score: 60.0, passedChecks: 3, totalChecks: 5 },
      cost: { score: 62.5, passedChecks: 3, totalChecks: 4 },
    },
    issues: { critical: 0, errors: 3, warnings: 6 },
    findings: [
      { ruleId: 'SEC-003', ruleName: 'Privilege Escalation Desabilitado', severity: 'error', message: 'allowPrivilegeEscalation nao configurado', remediation: 'Configure allowPrivilegeEscalation: false', remediable: false },
      { ruleId: 'SEC-004', ruleName: 'Capabilities Reduzidas', severity: 'warning', message: 'Capabilities nao reduzidas', remediation: 'Adicione drop: [ALL]', remediable: false },
      { ruleId: 'RES-012', ruleName: 'NetworkPolicy Aplicada', severity: 'warning', message: 'NetworkPolicy nao encontrada', remediation: 'Crie NetworkPolicy para restringir trafego', remediable: false },
    ],
    lastEvaluated: '2024-01-20T10:15:00Z',
    monthlyCostUsd: 1800,
    cpuEfficiencyPct: 62,
    memoryEfficiencyPct: 55,
    wasteUsd: 640,
    sloCount: 1,
    sloHealthy: 0,
    trend: 'down',
    scoreHistory: makeHistory(65),
  },
  {
    id: 'search-api',
    name: 'search-api',
    namespace: 'production',
    kind: 'Deployment',
    squad: 'search',
    product: 'Marketplace',
    domain: 'Commerce',
    owner: 'search-team',
    techLead: 'julia.santos@example.com',
    tier: 'tier-2',
    overallScore: 78.9,
    pillarScores: {
      resilience: { score: 82.8, passedChecks: 10, totalChecks: 14 },
      security: { score: 82.1, passedChecks: 3, totalChecks: 4 },
      compliance: { score: 66.7, passedChecks: 2, totalChecks: 3 },
      performance: { score: 71.4, passedChecks: 1, totalChecks: 2 },
      operational: { score: 80.0, passedChecks: 4, totalChecks: 5 },
      cost: { score: 75.0, passedChecks: 3, totalChecks: 4 },
    },
    issues: { critical: 0, errors: 1, warnings: 4 },
    findings: [
      { ruleId: 'COMP-001', ruleName: "Label 'team' obrigatorio", severity: 'error', message: "Label 'team' nao encontrado", remediation: "Adicione labels.team ao Deployment", remediable: false },
    ],
    lastEvaluated: '2024-01-20T14:00:00Z',
    monthlyCostUsd: 680,
    cpuEfficiencyPct: 70,
    memoryEfficiencyPct: 66,
    wasteUsd: 180,
    sloCount: 2,
    sloHealthy: 2,
    trend: 'stable',
    scoreHistory: makeHistory(79),
  },
  {
    id: 'recommendation-engine',
    name: 'recommendation-engine',
    namespace: 'production',
    kind: 'Deployment',
    squad: 'ml',
    product: 'Marketplace',
    domain: 'Commerce',
    owner: 'ml-team',
    techLead: 'thiago.carvalho@example.com',
    tier: 'tier-1',
    overallScore: 43.1,
    pillarScores: {
      resilience: { score: 43.0, passedChecks: 5, totalChecks: 14 },
      security: { score: 25.0, passedChecks: 1, totalChecks: 4 },
      compliance: { score: 33.3, passedChecks: 1, totalChecks: 3 },
      performance: { score: 57.1, passedChecks: 1, totalChecks: 2 },
      operational: { score: 40.0, passedChecks: 2, totalChecks: 5 },
      cost: { score: 50.0, passedChecks: 2, totalChecks: 4 },
    },
    issues: { critical: 1, errors: 6, warnings: 5 },
    findings: [
      { ruleId: 'SEC-001', ruleName: 'Imagem com Tag Especifica', severity: 'error', message: 'Usando :latest', remediation: 'Use tag especifica', remediable: false },
      { ruleId: 'SEC-002', ruleName: 'ReadOnly Root Filesystem', severity: 'critical', message: 'Root filesystem gravavel em container privilegiado', remediation: 'Configure readOnlyRootFilesystem: true e remova privilegios', remediable: false },
      { ruleId: 'SEC-003', ruleName: 'Privilege Escalation Desabilitado', severity: 'error', message: 'Privilege escalation habilitado', remediation: 'Configure allowPrivilegeEscalation: false', remediable: false },
      { ruleId: 'RES-001', ruleName: 'Liveness Probe', severity: 'error', message: 'Liveness probe nao configurada', remediation: 'Configure livenessProbe no container', remediable: false },
      { ruleId: 'RES-002', ruleName: 'Readiness Probe', severity: 'error', message: 'Readiness probe nao configurada', remediation: 'Configure readinessProbe no container', remediable: false },
      { ruleId: 'RES-013', ruleName: 'Minimo 2 Replicas', severity: 'warning', message: 'Apenas 1 replica', remediation: 'Aumente para 2+ replicas', remediable: true },
    ],
    remediationPR: { prNumber: 138, prUrl: 'https://github.com/org/marketplace/pull/138', prBranch: 'titlis/remediation/production-recommendation-engine', status: 'open', issuesFixed: ['RES-013', 'RES-001', 'RES-002'], createdAt: '2024-01-18T09:00:00Z' },
    lastEvaluated: '2024-01-20T13:30:00Z',
    monthlyCostUsd: 2400,
    cpuEfficiencyPct: 38,
    memoryEfficiencyPct: 42,
    wasteUsd: 1300,
    sloCount: 2,
    sloHealthy: 0,
    trend: 'down',
    scoreHistory: makeHistory(43),
  },
]

export const slos: SLO[] = [
  { id: 'slo-001', name: 'Payment API Availability', service: 'payment-api', namespace: 'production', squad: 'payments', target: 99.9, current: 99.95, status: 'healthy', errorBudgetRemaining: 98.2, framework: 'fastapi', lastUpdated: '2024-01-20T14:00:00Z', burnRate7d: 0.8, burnRate1h: 0.3, history: makeHistory(99.9) },
  { id: 'slo-002', name: 'Payment API Latency P99', service: 'payment-api', namespace: 'production', squad: 'payments', target: 99.5, current: 99.7, status: 'healthy', errorBudgetRemaining: 95.1, framework: 'fastapi', lastUpdated: '2024-01-20T14:00:00Z', burnRate7d: 1.1, burnRate1h: 0.9, history: makeHistory(99.5) },
  { id: 'slo-003', name: 'Order Service Availability', service: 'order-service', namespace: 'production', squad: 'orders', target: 99.5, current: 99.1, status: 'at_risk', errorBudgetRemaining: 23.4, framework: 'wsgi', lastUpdated: '2024-01-20T13:50:00Z', burnRate7d: 3.2, burnRate1h: 4.1, history: makeHistory(99.0) },
  { id: 'slo-004', name: 'User Auth Availability', service: 'user-auth', namespace: 'production', squad: 'identity', target: 99.99, current: 100.0, status: 'healthy', errorBudgetRemaining: 100.0, framework: 'fastapi', lastUpdated: '2024-01-20T14:10:00Z', burnRate7d: 0.1, burnRate1h: 0.0, history: makeHistory(99.99) },
  { id: 'slo-005', name: 'Analytics Ingestion Throughput', service: 'analytics-ingestion', namespace: 'data', squad: 'data', target: 99.0, current: 97.8, status: 'breached', errorBudgetRemaining: 0.0, framework: 'custom', lastUpdated: '2024-01-20T10:15:00Z', burnRate7d: 8.4, burnRate1h: 12.3, history: makeHistory(97) },
  { id: 'slo-006', name: 'Search API Latency', service: 'search-api', namespace: 'production', squad: 'search', target: 99.5, current: 99.6, status: 'healthy', errorBudgetRemaining: 88.7, framework: 'aiohttp', lastUpdated: '2024-01-20T14:00:00Z', burnRate7d: 1.4, burnRate1h: 0.7, history: makeHistory(99.6) },
  { id: 'slo-007', name: 'Recommendation Availability', service: 'recommendation-engine', namespace: 'production', squad: 'ml', target: 99.5, current: 98.1, status: 'breached', errorBudgetRemaining: 0.0, framework: 'custom', lastUpdated: '2024-01-20T13:30:00Z', burnRate7d: 9.1, burnRate1h: 15.2, history: makeHistory(98) },
]

export const squadSummaries: SquadSummary[] = [
  { squad: 'payments', product: 'Core Banking', domain: 'Financial', appCount: 2, avgScore: 85.2, criticalApps: 0, openPRs: 1, reliabilityScore: 88, securityScore: 89, trend: 'up' },
  { squad: 'orders', product: 'Marketplace', domain: 'Commerce', appCount: 3, avgScore: 63.4, criticalApps: 1, openPRs: 2, reliabilityScore: 62, securityScore: 40, trend: 'down' },
  { squad: 'identity', product: 'Identity Platform', domain: 'Security', appCount: 1, avgScore: 93.7, criticalApps: 0, openPRs: 0, reliabilityScore: 96, securityScore: 100, trend: 'stable' },
  { squad: 'platform', product: 'Platform Infra', domain: 'Infrastructure', appCount: 2, avgScore: 72.1, criticalApps: 0, openPRs: 1, reliabilityScore: 75, securityScore: 75, trend: 'up' },
  { squad: 'data', product: 'Data Platform', domain: 'Analytics', appCount: 1, avgScore: 65.8, criticalApps: 0, openPRs: 0, reliabilityScore: 64, securityScore: 53, trend: 'down' },
  { squad: 'ml', product: 'Marketplace', domain: 'Commerce', appCount: 1, avgScore: 43.1, criticalApps: 1, openPRs: 1, reliabilityScore: 43, securityScore: 25, trend: 'down' },
  { squad: 'search', product: 'Marketplace', domain: 'Commerce', appCount: 1, avgScore: 78.9, criticalApps: 0, openPRs: 0, reliabilityScore: 83, securityScore: 82, trend: 'stable' },
  { squad: 'catalog', product: 'Marketplace', domain: 'Commerce', appCount: 1, avgScore: 91.2, criticalApps: 0, openPRs: 0, reliabilityScore: 92, securityScore: 96, trend: 'stable' },
]

export const platformSummary: PlatformSummary = {
  totalApps: 8,
  avgScore: 73.6,
  criticalApps: 2,
  excellentApps: 2,
  goodApps: 2,
  warningApps: 2,
  openPRs: 3,
  totalFindings: { critical: 1, errors: 18, warnings: 30 },
  sloCompliance: 71.4,
  totalMonthlyCost: 8040,
  scoreHistory: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (30 - i) * 86400000).toISOString().split('T')[0],
    score: 68 + Math.random() * 12,
    critical: Math.floor(1 + Math.random() * 3),
  })),
}
