FROM node:22-alpine AS build
WORKDIR /app

ARG VITE_API_URL=http://localhost:30081/v1
ARG VITE_APP_ENV=production
ARG VITE_AUTH_MODE=okta
ARG VITE_OKTA_ISSUER=https://jeitto.okta.com
ARG VITE_OKTA_CLIENT_ID=
ARG VITE_OKTA_AUDIENCE=api://titlis
ARG VITE_OKTA_REDIRECT_URI=https://confia.jeitto.com.br/login/callback
ARG VITE_OKTA_POST_LOGOUT_REDIRECT_URI=https://confia.jeitto.com.br/login
ARG VITE_OKTA_TENANT_SLUG=jeitto

ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_APP_ENV=${VITE_APP_ENV}
ENV VITE_AUTH_MODE=${VITE_AUTH_MODE}
ENV VITE_OKTA_ISSUER=${VITE_OKTA_ISSUER}
ENV VITE_OKTA_CLIENT_ID=${VITE_OKTA_CLIENT_ID}
ENV VITE_OKTA_AUDIENCE=${VITE_OKTA_AUDIENCE}
ENV VITE_OKTA_REDIRECT_URI=${VITE_OKTA_REDIRECT_URI}
ENV VITE_OKTA_POST_LOGOUT_REDIRECT_URI=${VITE_OKTA_POST_LOGOUT_REDIRECT_URI}
ENV VITE_OKTA_TENANT_SLUG=${VITE_OKTA_TENANT_SLUG}

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
