apiVersion: titlis.io/v1
kind: ServiceDefinition
metadata:
  name: titlis-ui
  workload_match:
    namespaces: [titlis-preprod, titlis-prod]
    name_pattern: "^titlis-ui(-.*)?$"
spec:
  owner:
    team: platform
    contacts:
      - type: slack
        value: "#platform-oncall"
  gitops:
    layout: folder_per_env
    paths:
      dev:
        path: manifest/kubernetes/develop/deploy.yaml
        base_branch: develop
      hml:
        path: manifest/kubernetes/release/deploy.yaml
        base_branch: release
      prd:
        path: manifest/kubernetes/main/deploy.yaml
        base_branch: main
    pipeline_watcher: argocd
  remediation:
    enabled: true
    overrides:
      hpa_environment_templates:
        dev: { min: 1, max: 2, target_cpu: 80 }
        hml: { min: 1, max: 3, target_cpu: 80 }
        prd: { min: 2, max: 6, target_cpu: 70 }
