metadata:
  name: titlis-ui
  workload_match:
    namespaces: [titlis-preprod, titlis-prod]
    name_pattern: "^titlis-ui$"
spec:
  owner:
    team: platform
    contacts:
      - type: slack
        value: "#platform-oncall"
  gitops:
    paths:
      dev:
        path: manifest/kubernetes/develop/deploy.yaml
        base_branch: develop
      hml:
        path: manifest/kubernetes/release/deploy.yaml
        base_branch: release
      prd:
        path: manifest/kubernetes/main/deploy.yaml
        base_branch: main
  remediation:
    enabled: true
