apiVersion: apps/v1
kind: Deployment
metadata:
  name: titlis-ui
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titlis-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: titlis-ui
        tags.datadoghq.com/env: "preprod"
        tags.datadoghq.com/service: "titlis-ui"
        tags.datadoghq.com/version: "__IMAGE_TAG__"
    spec:
      containers:
        - name: titlis-ui
          image: __DOCKERHUB_USER__/titlis-ui:__IMAGE_TAG__
          imagePullPolicy: __IMAGE_PULL_POLICY__
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: titlis-ui
  namespace: __NAMESPACE__
spec:
  type: NodePort
  selector:
    app: titlis-ui
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      nodePort: 30080
      name: http
